name: Autobuild rmfakecloud

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 8 * * 5


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Clone source code
        run: |
          git clone https://github.com/ddvk/rmfakecloud.git fakecloud
          pwd

      - name: Build 
        run: |
          cp -rf Makefile fakecloud/Makefile
          cd fakecloud
          make all
        
      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        with:
          name: framebuffer
          path: dist/*
