name: Autobuild dummycloud

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 8 * * 5


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version: ^1.17
        id: go
        
      - name: Checkout
        uses: actions/checkout@v2.5.0
        
      - name: Clone source code
        run: |
          git clone https://github.com/ddvk/rmfakecloud.git fakecloud
          pwd
          ls

      - name: Build 
        run: |
          cp -rf Makefile fakecloud/Makefile
          cd fakecloud
          CI=false make all
          upx --lzma --best /home/runner/work/dummycloud/dummycloud/fakecloud/dist/rmfakecloud-mipsle
        
      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        with:
          name: framebuffer
          path: /home/runner/work/dummycloud/dummycloud/fakecloud/dist/*
